name: CURL_BOT_SERVER

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest

    #            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \

    steps:
    - run: |
        curl --write-out '%{http_code}' \
            --request POST \
            --header 'content-type: application/json' \
            --url 'cloud.ecsimsw.com:7777/${{ github.actor }}'